site_name: Dhruvam's Blog
base_url: "/"
docs_dir: posts
theme:
  name: material
  icon:
    logo: material/pound
  features:
    - content.code.annotate 
    - navigation.expand
  palette: 

    - media: "(prefers-color-scheme: light)"
      accent: cyan
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - tags

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
 - assets/css/style.css
